# Generated by Django 2.2 on 2021-06-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamingNewsApp', '0002_comment_forum_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images')),
            ],
        ),
    ]
