# Generated by Django 2.2 on 2021-06-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamingNewsApp', '0004_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
    ]
