# Generated by Django 2.2 on 2021-06-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamingNewsApp', '0009_auto_20210609_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
    ]
